# Generated by Django 4.2.4 on 2023-08-20 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Chitungwiza', 'Chitungwiza'), ('Mutare', 'Mutare'), ('Gweru', 'Gweru'), ('Epworth', 'Epworth'), ('Kwekwe', 'Kwekwe'), ('Kadoma', 'Kadoma'), ('Masvingo', 'Masvingo'), ('Chinhoyi', 'Chinhoyi'), ('Marondera', 'Marondera'), ('Norton', 'Norton'), ('Chegutu', 'Chegutu'), ('Bindura', 'Bindura'), ('Beitbridge', 'Beitbridge')], default='Gweru', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='house_number',
            field=models.IntegerField(default=4790),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=45.6, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=45.3, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0782841339', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Manicaland', 'Manicaland'), ('Mashonaland Central', 'Mashonaland Central'), ('Mashonaland East', 'Mashonaland East'), ('Mashonaland West', 'Mashonaland West'), ('Masvingo', 'Masvingo'), ('Matabeleland North', 'Matabeleland North'), ('Matabeleland South', 'Matabeleland South'), ('Midlands', 'Midlands')], default='Midlands', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='Gudo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='suburb',
            field=models.CharField(default='Mkoba 12', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('middleman', 'Middleman'), ('admin', 'Administrator')], default='admin', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
