# Generated by Django 4.2.4 on 2024-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_lat_alter_user_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer')], default='customer', max_length=45),
        ),
    ]
