# Generated by Django 4.2.4 on 2023-08-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting-delivery', 'Awaiting Delivery'), ('delivered', 'Delivered'), ('ready-for-shipping', 'Ready For Delivery'), ('delivery-in-progress', 'Sent Out'), ('cancelled', 'Cancelled'), ('failed', 'failed')], default='pending', max_length=45),
        ),
    ]
