# Generated by Django 4.2.4 on 2023-09-03 17:04

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "430x360",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AddField(
            model_name="productrequest",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "430x360",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="unassigned",
                max_length=45,
            ),
        ),
    ]
