# Generated by Django 4.2.4 on 2023-09-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_deal_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="products",
        ),
        migrations.CreateModel(
            name="DealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_items",
                        to="core.deal",
                    ),
                ),
            ],
        ),
    ]
