# Generated by Django 4.2.4 on 2023-12-18 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='producer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting-delivery', 'Awaiting Delivery'), ('delivered', 'Delivered'), ('ready-for-shipping', 'Ready For Delivery'), ('delivery-in-progress', 'Sent Out'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=45),
        ),
    ]
