# Generated by Django 4.2.4 on 2023-09-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_dealitem_deal_alter_dealitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="unassigned_at",
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=45,
            ),
        ),
    ]
