# Generated by Django 4.2.4 on 2024-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_order_alter_payment_paynow_poll_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='payments', to='core.order'),
        ),
    ]
