# Generated by Django 4.2.4 on 2023-09-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_deal_assigned_at_remove_deal_unassigned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deal",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="core.deal",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(default="Test test", max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted"),
                    ("sealed", "Sealed"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=45,
            ),
        ),
    ]
