# Generated by Django 4.2.4 on 2023-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_payment_user_payment_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paynow_id",
            new_name="paynow_poll_url",
        ),
        migrations.AddField(
            model_name="payment",
            name="paynow_redirect_url",
            field=models.CharField(default="https://google.com", max_length=255),
            preserve_default=False,
        ),
    ]
