# Generated by Django 4.2.4 on 2023-10-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_rename_paynow_id_payment_paynow_poll_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
