# Generated by Django 4.2.4 on 2023-10-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_alter_deal_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
