# Generated by Django 4.2.4 on 2023-10-30 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_withdrawal_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="withdrawal",
            old_name="inbucks_qrcode",
            new_name="innbucks_qrcode",
        ),
    ]
