# Generated by Django 4.2.4 on 2023-11-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dealbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
